# Generated by Django 3.1.2 on 2020-11-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre:')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo')),
                ('phono', models.IntegerField(verbose_name='Numero Telefono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
