# Generated by Django 3.1.2 on 2020-11-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phono',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=123456, max_length=12, verbose_name='Numero telefonico'),
            preserve_default=False,
        ),
    ]
