# Generated by Django 3.1.2 on 2020-11-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/', verbose_name='Imagen servicio')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('body', models.TextField(verbose_name='Detalles')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
