# Generated by Django 3.1.2 on 2020-11-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client/', verbose_name='Imagen CLiente')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Empresa')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
