# Generated by Django 3.1.2 on 2020-12-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='social/', verbose_name='Fotos')),
                ('title', models.CharField(max_length=50, verbose_name='Nombre de la red')),
                ('url', models.URLField(verbose_name='Direccion de la red')),
            ],
        ),
    ]
